# Generated by Django 5.1.1 on 2024-10-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTest',
            new_name='PostText',
        ),
        migrations.RenameField(
            model_name='postphoto',
            old_name='image',
            new_name='photo',
        ),
    ]
